"""Dependency-free SAP Local Protected Storage (LPS) containers.

SSFS enhanced key protection stores its key-encryption key inside an instance
local ``.LKY`` file. The real LKY payload is an LPS container. Portable
fallback protection is implemented here; DPAPI and TPM protection remain
platform-bound and use an explicit provider callback.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import struct
import zlib
from dataclasses import dataclass
from enum import IntEnum
from typing import Callable, Optional

from .crypto import AES_BLOCK_SIZE, aes128_cbc, triple_des_ecb
from .errors import IntegrityError, UnsupportedFormatError

LPS_MAX_CONTEXT_LENGTH = 40
LPS_MAX_RESTRICTION_LENGTH = 1024
LPS_HMAC_SIZE = 20
LPS_CRC_SIZE = 4


class LPSProtection(IntEnum):
    """Platform protection selector stored in an LPS container."""

    FALLBACK = 0
    DPAPI = 1
    TPM = 2


LPSUnprotector = Callable[[LPSProtection, bytes, bytes, bytes], bytes]
LPSProtector = Callable[[LPSProtection, bytes, bytes, bytes], bytes]
RestrictionValidator = Callable[[bytes], bool]


def _take_u16(blob: bytes, offset: int, label: str) -> tuple[int, int]:
    if offset + 2 > len(blob):
        raise IntegrityError(f"truncated LPS {label} length")
    return struct.unpack(">H", blob[offset : offset + 2])[0], offset + 2


def _take_field(blob: bytes, offset: int, length: int, label: str) -> tuple[bytes, int]:
    end = offset + length
    if end > len(blob):
        raise IntegrityError(f"truncated LPS {label}")
    return blob[offset:end], end


def _lps_seed_material() -> tuple[bytes, int]:
    # This deterministic sequence is generated by the same small LCG present
    # in CommonCryptoLib. Keeping the derivation, rather than a copied key
    # literal, documents where the portable fallback material comes from.
    state = 101
    material = bytearray()
    for _ in range(24):
        state = (state * 20001) % 65537
        material.append(state & 0xFF)
    return bytes(material), state


def _lps_default_key(version: int, context: bytes) -> bytes:
    material, state = _lps_seed_material()
    if version == 1:
        transformed_context = b"".join(bytes((value, 0)) for value in context[:40])
        output_size = 24
    elif version == 2:
        transformed_context = context[:40]
        output_size = 16
    else:
        raise UnsupportedFormatError(f"unsupported LPS version {version}")

    digest_key = hashlib.sha1(material).digest()
    output = bytearray(hmac.new(digest_key, transformed_context, hashlib.sha1).digest())
    while len(output) < output_size:
        state = (state * 20001) % 65537
        output.append(state & 0xFF)
    return bytes(output[:output_size])


def _lps_hmac(encryption_key: bytes, authenticated: bytes) -> bytes:
    return hmac.new(hashlib.sha1(encryption_key).digest(), authenticated, hashlib.sha1).digest()


def _windows_dpapi_unprotect(protected: bytes) -> bytes:
    if os.name != "nt":
        raise UnsupportedFormatError(
            "this LPS key uses Windows DPAPI and can only be unlocked on its Windows host "
            "or through an explicit lps_unprotector callback"
        )

    # ctypes is part of Python's standard library; importing lazily keeps the
    # package portable on systems that do not expose Windows APIs.
    import ctypes
    from ctypes import wintypes

    class DataBlob(ctypes.Structure):
        _fields_ = (
            ("cbData", wintypes.DWORD),
            ("pbData", ctypes.POINTER(ctypes.c_ubyte)),
        )

    input_buffer = (ctypes.c_ubyte * len(protected)).from_buffer_copy(protected)
    input_blob = DataBlob(len(protected), input_buffer)
    output_blob = DataBlob()
    crypt32 = ctypes.WinDLL("crypt32", use_last_error=True)
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    crypt32.CryptUnprotectData.argtypes = (
        ctypes.POINTER(DataBlob),
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        wintypes.DWORD,
        ctypes.POINTER(DataBlob),
    )
    crypt32.CryptUnprotectData.restype = wintypes.BOOL
    if not crypt32.CryptUnprotectData(
        ctypes.byref(input_blob),
        None,
        None,
        None,
        None,
        0,
        ctypes.byref(output_blob),
    ):
        error = ctypes.get_last_error()
        raise IntegrityError(f"Windows DPAPI could not unlock the LPS key (error {error})")
    try:
        return ctypes.string_at(output_blob.pbData, output_blob.cbData)
    finally:
        kernel32.LocalFree(output_blob.pbData)


@dataclass(frozen=True)
class LPSBlob:
    """Decoded SAP LPS v1/v2 protected-data container."""

    version: int
    protection: LPSProtection
    context: bytes
    restriction: bytes
    encrypted_key: bytes
    unknown: bytes
    encrypted_data: bytes
    mac: bytes
    crc32: bytes

    @classmethod
    def parse(cls, blob: bytes) -> "LPSBlob":
        if len(blob) < 1 + 1 + 2 + 2 + 2 + 2 + 2 + LPS_HMAC_SIZE + LPS_CRC_SIZE:
            raise IntegrityError("LPS container is shorter than its minimum structure")
        expected_crc = zlib.crc32(blob[:-LPS_CRC_SIZE]).to_bytes(LPS_CRC_SIZE, "big")
        if not hmac.compare_digest(blob[-LPS_CRC_SIZE:], expected_crc):
            raise IntegrityError("LPS container CRC32 is invalid")

        version = blob[0]
        if version not in (1, 2):
            raise UnsupportedFormatError(f"unsupported LPS version {version}")
        try:
            protection = LPSProtection(blob[1])
        except (TypeError, ValueError) as exc:
            raise UnsupportedFormatError(f"unsupported LPS protection type {blob[1]}") from exc

        payload_end = len(blob) - LPS_HMAC_SIZE - LPS_CRC_SIZE
        offset = 2
        context_length, offset = _take_u16(blob, offset, "context")
        if context_length > LPS_MAX_CONTEXT_LENGTH:
            raise UnsupportedFormatError(
                f"LPS context is longer than {LPS_MAX_CONTEXT_LENGTH} bytes"
            )
        context, offset = _take_field(blob, offset, context_length, "context")

        restriction_length, offset = _take_u16(blob, offset, "restriction")
        if restriction_length > LPS_MAX_RESTRICTION_LENGTH:
            raise UnsupportedFormatError(
                f"LPS restriction is longer than {LPS_MAX_RESTRICTION_LENGTH} bytes"
            )
        restriction, offset = _take_field(blob, offset, restriction_length, "restriction")

        encrypted_key_length, offset = _take_u16(blob, offset, "encrypted-key")
        encrypted_key, offset = _take_field(
            blob, offset, encrypted_key_length, "encrypted key"
        )
        unknown_length, offset = _take_u16(blob, offset, "intermediate")
        unknown, offset = _take_field(blob, offset, unknown_length, "intermediate data")
        encrypted_data_length, offset = _take_u16(blob, offset, "encrypted-data")
        encrypted_data, offset = _take_field(
            blob, offset, encrypted_data_length, "encrypted data"
        )
        if offset != payload_end:
            raise IntegrityError(
                f"LPS container has {payload_end - offset} unexpected byte(s) before its HMAC"
            )
        mac = blob[payload_end : payload_end + LPS_HMAC_SIZE]
        return cls(
            version,
            protection,
            context,
            restriction,
            encrypted_key,
            unknown,
            encrypted_data,
            mac,
            blob[-LPS_CRC_SIZE:],
        )

    def _body(self) -> bytes:
        if self.version not in (1, 2):
            raise UnsupportedFormatError(f"unsupported LPS version {self.version}")
        if len(self.context) > LPS_MAX_CONTEXT_LENGTH:
            raise ValueError(
                f"LPS context must be at most {LPS_MAX_CONTEXT_LENGTH} bytes"
            )
        if len(self.restriction) > LPS_MAX_RESTRICTION_LENGTH:
            raise ValueError(
                f"LPS restriction must be at most {LPS_MAX_RESTRICTION_LENGTH} bytes"
            )
        for label, value in (
            ("encrypted key", self.encrypted_key),
            ("intermediate data", self.unknown),
            ("encrypted data", self.encrypted_data),
        ):
            if len(value) > 0xFFFF:
                raise ValueError(f"LPS {label} exceeds the 16-bit length field")
        return b"".join(
            (
                bytes((self.version, int(self.protection))),
                struct.pack(">H", len(self.context)),
                self.context,
                struct.pack(">H", len(self.restriction)),
                self.restriction,
                struct.pack(">H", len(self.encrypted_key)),
                self.encrypted_key,
                struct.pack(">H", len(self.unknown)),
                self.unknown,
                struct.pack(">H", len(self.encrypted_data)),
                self.encrypted_data,
            )
        )

    def to_bytes(self) -> bytes:
        body = self._body()
        if len(self.mac) != LPS_HMAC_SIZE:
            raise IntegrityError("LPS HMAC-SHA1 must be exactly 20 bytes")
        content = body + self.mac
        expected_crc = zlib.crc32(content).to_bytes(LPS_CRC_SIZE, "big")
        if self.crc32 and not hmac.compare_digest(self.crc32, expected_crc):
            raise IntegrityError("refusing to serialize an LPS container with an invalid CRC32")
        return content + expected_crc

    def _decrypt_encryption_key(
        self,
        *,
        lps_unprotector: Optional[LPSUnprotector],
    ) -> bytes:
        if self.protection is LPSProtection.FALLBACK:
            default_key = _lps_default_key(self.version, self.context)
            try:
                if self.version == 1:
                    clear = triple_des_ecb(
                        self.encrypted_key, default_key, decrypt=True
                    )
                    expected_size = 24
                else:
                    clear = aes128_cbc(
                        self.encrypted_key, default_key, decrypt=True
                    )
                    expected_size = 16
            except ValueError as exc:
                raise IntegrityError(
                    "LPS protected encryption key has an invalid block length"
                ) from exc
        elif lps_unprotector is not None:
            clear = lps_unprotector(
                self.protection,
                self.encrypted_key,
                self.context,
                self.restriction,
            )
            expected_size = 24 if self.version == 1 else 16
        elif self.protection is LPSProtection.DPAPI:
            clear = _windows_dpapi_unprotect(self.encrypted_key)
            expected_size = 24 if self.version == 1 else 16
        else:
            raise UnsupportedFormatError(
                "this LPS key is TPM-bound; unlock it on the registered host or provide "
                "an explicit lps_unprotector callback"
            )
        if len(clear) != expected_size:
            raise IntegrityError(
                f"LPS encryption key must decode to {expected_size} bytes, got {len(clear)}"
            )
        return clear

    def decrypt(
        self,
        *,
        expected_context: Optional[bytes] = None,
        lps_unprotector: Optional[LPSUnprotector] = None,
        restriction_validator: Optional[RestrictionValidator] = None,
    ) -> bytes:
        """Validate and decrypt the protected value.

        Portable fallback protection is handled internally. DPAPI uses the
        Windows standard API when available. TPM or application-specific
        platform protection requires ``lps_unprotector``.
        """

        if expected_context is not None and not hmac.compare_digest(
            self.context, expected_context
        ):
            raise IntegrityError(
                f"LPS context {self.context!r} does not match expected {expected_context!r}"
            )
        if self.restriction:
            if restriction_validator is None:
                raise UnsupportedFormatError(
                    "LPS container has a platform restriction; provide a restriction_validator "
                    "on the original host"
                )
            if not restriction_validator(self.restriction):
                raise IntegrityError("LPS platform restriction does not match this host")

        encryption_key = self._decrypt_encryption_key(
            lps_unprotector=lps_unprotector
        )
        expected_mac = _lps_hmac(encryption_key, self._body())
        if not hmac.compare_digest(self.mac, expected_mac):
            raise IntegrityError("LPS container HMAC-SHA1 is invalid")

        try:
            if self.version == 1:
                clear = triple_des_ecb(
                    self.encrypted_data, encryption_key, decrypt=True
                )
            else:
                clear = aes128_cbc(
                    self.encrypted_data, encryption_key, decrypt=True
                )
        except ValueError as exc:
            raise IntegrityError("LPS encrypted data has an invalid block length") from exc
        if not clear:
            raise IntegrityError("LPS decrypted value is empty")
        prefix_length = clear[0] + 1
        if prefix_length > len(clear):
            raise IntegrityError("LPS decrypted value has an invalid random-prefix length")
        return clear[prefix_length:]

    @classmethod
    def protect(
        cls,
        value: bytes,
        *,
        context: bytes,
        protection: LPSProtection = LPSProtection.FALLBACK,
        restriction: bytes = b"",
        version: int = 2,
        lps_protector: Optional[LPSProtector] = None,
        random_bytes: Callable[[int], bytes] = os.urandom,
    ) -> "LPSBlob":
        """Create LPS material using fallback or an explicit host provider.

        Fallback keeps its root material derivable from the context. DPAPI/TPM
        creation requires ``lps_protector`` so platform scope and provisioning
        policy are never guessed by this format library.
        """

        if version not in (1, 2):
            raise UnsupportedFormatError(f"cannot create LPS version {version}")
        if len(context) > LPS_MAX_CONTEXT_LENGTH:
            raise ValueError(f"LPS context must be at most {LPS_MAX_CONTEXT_LENGTH} bytes")
        if len(restriction) > LPS_MAX_RESTRICTION_LENGTH:
            raise ValueError(
                f"LPS restriction must be at most {LPS_MAX_RESTRICTION_LENGTH} bytes"
            )
        try:
            protection = LPSProtection(protection)
        except (TypeError, ValueError) as exc:
            raise UnsupportedFormatError(
                f"unsupported LPS protection type {protection}"
            ) from exc
        key_size = 24 if version == 1 else 16
        block_size = 8 if version == 1 else AES_BLOCK_SIZE
        encryption_key = random_bytes(key_size)
        if len(encryption_key) != key_size:
            raise ValueError("random source returned the wrong LPS encryption-key length")
        if protection is LPSProtection.FALLBACK:
            default_key = _lps_default_key(version, context)
            if version == 1:
                encrypted_key = triple_des_ecb(encryption_key, default_key)
            else:
                encrypted_key = aes128_cbc(encryption_key, default_key)
        else:
            if lps_protector is None:
                raise UnsupportedFormatError(
                    f"LPS {protection.name} creation requires an explicit "
                    "lps_protector callback"
                )
            encrypted_key = lps_protector(
                protection,
                encryption_key,
                context,
                restriction,
            )
            if not isinstance(encrypted_key, bytes) or not encrypted_key:
                raise ValueError(
                    "lps_protector must return a nonempty bytes object"
                )

        padding_length = (-(1 + len(value))) % block_size
        padding = random_bytes(padding_length)
        if len(padding) != padding_length:
            raise ValueError("random source returned the wrong LPS padding length")
        clear = bytes((padding_length,)) + padding + value
        if version == 1:
            encrypted_data = triple_des_ecb(clear, encryption_key)
        else:
            encrypted_data = aes128_cbc(clear, encryption_key)

        provisional = cls(
            version=version,
            protection=protection,
            context=context,
            restriction=restriction,
            encrypted_key=encrypted_key,
            unknown=b"",
            encrypted_data=encrypted_data,
            mac=b"",
            crc32=b"",
        )
        mac = _lps_hmac(encryption_key, provisional._body())
        content = provisional._body() + mac
        return cls(
            version=version,
            protection=protection,
            context=context,
            restriction=restriction,
            encrypted_key=encrypted_key,
            unknown=b"",
            encrypted_data=encrypted_data,
            mac=mac,
            crc32=zlib.crc32(content).to_bytes(LPS_CRC_SIZE, "big"),
        )

    @classmethod
    def protect_fallback(
        cls,
        value: bytes,
        *,
        context: bytes,
        version: int = 2,
        random_bytes: Callable[[int], bytes] = os.urandom,
    ) -> "LPSBlob":
        """Create portable fallback LPS material for interoperability."""

        return cls.protect(
            value,
            context=context,
            protection=LPSProtection.FALLBACK,
            version=version,
            random_bytes=random_bytes,
        )
