def run():
    print("    [SAPinst - Port 21213 (Secure Installation UI over HTTPS)]")
    print("    ------------------------------------------------------------")
    print("    This module targets the TLS-secured SAPinst web interface, typically")
    print("    exposed on port 21213 during installation, system copy, or upgrades.")
    print()
    print("    ▸ SAPinst is the core tool for provisioning SAP systems. It supports")
    print("      interactive GUI-based installations via a web server it spawns locally.")
    print()
    print("    ▸ When SAPinst is launched in secure mode, it listens on port 21213")
    print("      and serves the same interface as 21212 — but over HTTPS.")
    print()
    print("    ▸ This UI allows privileged operations such as:")
    print("        - Instance provisioning")
    print("        - System migration (copy/export/import scenarios)")
    print("        - Hostname and SID configuration")
    print("        - DB/AS setup and OS integration")
    print()
    print("    ▸ The secure mode is intended for use via localhost with browser access.")
    print("      Remote access to this port — especially without client certs — is a sign")
    print("      of bad defaults, unsafe setup automation, or a dangerously open build.")
    print()
    print("    ▸ This check is a placeholder. Future versions will:")
    print("        - Attempt TLS negotiation and verify cert fingerprint")
    print("        - Query /sapinst and root endpoints for active wizard components")
    print("        - Extract install logs or stage indicators if available")
    print()
    print("    ▸ If port 21213 is open, it may indicate an active provisioning session,")
    print("      a left-behind install wizard, or worse — a post-setup system left")
    print("      with a privileged web shell listening in the background.")
    print("    ------------------------------------------------------------")

