def run():
    print("    [SAPinst - Port 21212 (Installation & System Copy UI)]")
    print("    ------------------------------------------------------------")
    print("    This module targets the SAPinst standalone web interface typically")
    print("    exposed on port 21212 during SAP installation or system migration.")
    print()
    print("    ▸ SAPinst is the installer and provisioning tool used to:")
    print("        - Install brand-new SAP systems")
    print("        - Perform system copies or migrations")
    print("        - Add new instances or services to an existing landscape")
    print()
    print("    ▸ When run in GUI mode, SAPinst spawns a local web server on port 21212,")
    print("      accessible via a browser (usually localhost or 127.0.0.1).")
    print()
    print("    ▸ In hardened systems, this port should only be accessible during controlled")
    print("      installation phases, and only from the console or loopback interface.")
    print("      If it's reachable over the network — that's a big red flag.")
    print()
    print("    ▸ The UI presents installation options such as:")
    print("        - ABAP/Java instance setup")
    print("        - DB schema initialization")
    print("        - SID configuration and hostname bindings")
    print()
    print("    ▸ This interface has been a vector in prior assessments for:")
    print("        - Path traversal vulnerabilities")
    print("        - RCE via crafted install scripts or logs")
    print("        - Post-install misconfig allowing unauthenticated reuse")
    print()
    print("    ▸ This check is a placeholder. Future versions will:")
    print("        - Detect if the SAPinst UI is active")
    print("        - Extract banner/version info from root and /sapinst path")
    print("        - Check for exposed control files, logs, or command options")
    print()
    print("    ▸ If port 21212 is open and the web UI responds, this host may be in")
    print("      the middle of provisioning — or worse, left wide open post-install.")
    print("    ------------------------------------------------------------")

