def run():
    print("    [SAP Message Server - 444NN Port Range (HTTPS)]")
    print("    ------------------------------------------------------------")
    print("    This module targets the SAP Message Server (MsgServer) listening")
    print("    over TLS via the 444NN port range (e.g. 44400, 44401, etc.).")
    print()
    print("    ▸ This is the HTTPS-secured counterpart of the 81NN MsgServer port.")
    print("      It exposes the same routing and system metadata interfaces,")
    print("      but over a TLS channel for encrypted transport.")
    print()
    print("    ▸ MsgServer coordinates instance communication and logon group routing.")
    print("      It's responsible for helping SAP clients (GUI, browser, or Dispatcher)")
    print("      determine which application server to connect to.")
    print()
    print("    ▸ 444NN is often used when:")
    print("        - SAP Web Dispatcher is configured to fetch instance info securely")
    print("        - Internal tools or scripts need encrypted logon group discovery")
    print("        - SAP systems are deployed in hardened zones (e.g., no plain HTTP)")
    print()
    print("    ▸ Typical endpoints exposed via MsgServer HTTPS include:")
    print("        - /msgserver/text/logon")
    print("        - /msgserver/html/group")
    print()
    print("    ▸ These pages reveal logon groups, app server roles, and priorities.")
    print("      They’re used by components like sapgui.exe and sapwebdisp to")
    print("      load balance users or services to the correct target instance.")
    print()
    print("    ▸ This check is a placeholder. Later versions will:")
    print("        - Perform TLS validation on 444NN")
    print("        - Pull and parse logon group metadata from MsgServer")
    print("        - Identify multi-instance landscapes and routing configs")
    print()
    print("    ▸ If 444NN is reachable, MsgServer is handling secure routing")
    print("      logic for NetWeaver — and you're likely in a multi-host setup.")
    print("    ------------------------------------------------------------")

