def run():
    print("    [SAP HTTP Interface - Port 80 (Generic Web Entry)]")
    print("    ------------------------------------------------------------")
    print("    This module targets port 80, the standard HTTP port. In SAP landscapes,")
    print("    if this port is open, it may serve as a public-facing entry point via:")
    print("        - SAP Web Dispatcher (proxy/load balancer)")
    print("        - SAP ICM (Internet Communication Manager)")
    print("        - SAP Message Server HTTP interface")
    print()
    print("    ▸ While not specific to SAP, port 80 is commonly used to provide clean")
    print("      HTTP access to SAP services without exposing high-numbered SAP ports.")
    print()
    print("    ▸ Common scenarios include:")
    print("        - Web Dispatcher forwarding to ICM at 8000/44300")
    print("        - A Java or ABAP stack configured to bind directly to :80")
    print("        - A reverse proxy that terminates at /sap/bc/ or /irj/portal")
    print()
    print("    ▸ If it responds with SAP headers, you can likely probe for:")
    print("        - /sap/bc/gui/sap/its/webgui (SAP GUI for HTML)")
    print("        - /sap/public/info (ICM info page)")
    print("        - /irj/portal (Enterprise Portal)")
    print("        - /nwa (NetWeaver Admin)")
    print()
    print("    ▸ This check is a placeholder. Future versions will:")
    print("        - Detect SAP stack behind port 80 via headers and content")
    print("        - Identify if Web Dispatcher is in play")
    print("        - Probe for redirect chains to 443NN or high ports")
    print()
    print("    ▸ If port 80 is open and leads to SAP content, this is likely an")
    print("      external-facing SAP service — and could reveal login pages,")
    print("      internal endpoints, or proxy misconfigurations.")
    print("    ------------------------------------------------------------")

