def run():
    print("    [SAP ICM - 80NN Port Range]")
    print("    ------------------------------------------------------------")
    print("    This module targets the SAP Internet Communication Manager (ICM)")
    print("    listening on ports in the 80NN range (e.g. 8000, 8001, etc.).")
    print()
    print("    ▸ ICM acts as the web gateway in SAP NetWeaver systems.")
    print("      It's responsible for handling incoming HTTP(S) requests and")
    print("      routing them internally to either ABAP or Java stacks.")
    print()
    print("    ▸ 80NN is the default for non-TLS HTTP traffic — usually tied")
    print("      to the ABAP stack. Requests here often hit /sap/bc/* paths.")
    print()
    print("    ▸ Common services exposed via 80NN include:")
    print("        - SAP GUI for HTML (/sap/bc/gui/sap/its/webgui)")
    print("        - Fiori Launchpad (/sap/bc/ui5_ui5/)")
    print("        - SICF-exposed web services (/sap/bc/srt/, /sap/public/...)")
    print("        - Business Client and dynamic BSP apps")
    print()
    print("    ▸ This port is crucial in interactive user access scenarios.")
    print("      It’s often paired with 443NN (HTTPS variant) or proxied via")
    print("      SAP Web Dispatcher in front-facing deployments.")
    print()
    print("    ▸ This check is a placeholder. In production, this module will:")
    print("        - Send methodical GET/HEAD requests to key SAP URIs")
    print("        - Detect ABAP stack presence via known headers and HTML")
    print("        - Log HTTP responses for SAP fingerprinting")
    print()
    print("    ▸ If 80NN is open and responsive, this system is likely hosting")
    print("      an ABAP instance capable of serving SAP GUI, Fiori, or service endpoints.")
    print("    ------------------------------------------------------------")

