def run():
    print("    [SAP Message Server - 81NN Port Range]")
    print("    ------------------------------------------------------------")
    print("    This module targets the SAP Message Server (MsgServer)")
    print("    listening over HTTP via the 81NN port range (e.g. 8100, 8101, etc.).")
    print()
    print("    ▸ The MsgServer acts as a central communication broker in SAP landscapes.")
    print("      It's responsible for handling message routing, load balancing, and")
    print("      information exchange between SAP application servers (dialog instances).")
    print()
    print("    ▸ The 81NN ports are specifically for the MsgServer's HTTP interface.")
    print("      While less common for user interaction, these ports are often used")
    print("      by tools and components that need to query SAP instance metadata or")
    print("      route to specific services (e.g. Web Dispatcher or load-balancing logic).")
    print()
    print("    ▸ These ports typically expose endpoints like:")
    print("        - /msgserver/text/logon (provides logon group info)")
    print("        - /msgserver/html/group (displays configured logon groups)")
    print()
    print("    ▸ In larger SAP systems, especially with multiple application servers,")
    print("      the MsgServer is used to determine which instance to route a user to")
    print("      based on system load or group configuration.")
    print()
    print("    ▸ The MsgServer is also critical for managing logon balancing when")
    print("      accessed via SAP GUI or web entry points.")
    print()
    print("    ▸ This check is a placeholder. In production, this module will:")
    print("        - Query known MsgServer HTTP paths")
    print("        - Extract instance and group config")
    print("        - Detect presence of routing logic")
    print()
    print("    ▸ If 81NN is open and responsive, the target likely participates in")
    print("      a distributed NetWeaver system and handles routing intelligence.")
    print("    ------------------------------------------------------------")

