def run():
    print("    [SAP Internet Transaction Server (ITS) - Legacy HTTP Ports]")
    print("    ------------------------------------------------------------")
    print("    This module targets standalone SAP ITS ports like 3950, 3951, 3954, 3964.")
    print("    These are used to expose SAP GUI transactions directly via a browser,")
    print("    without requiring a full SAP GUI client.")
    print()
    print("    ▸ ITS (Internet Transaction Server) was the original method for delivering")
    print("      SAP GUI in a browser. It renders classic Dynpro screens as HTML and")
    print("      manages web session state between user and backend ABAP.")
    print()
    print("    ▸ Common paths exposed via ITS include:")
    print("        - /scripts/wgate/webgui/!?~language=EN")
    print("        - /sap/bc/gui/sap/its/webgui")
    print("        - /sap/public/icmandir/its")
    print()
    print("    ▸ ITS can operate in two modes:")
    print("        - Integrated ITS: embedded in NetWeaver via ICM (modern approach)")
    print("        - Standalone ITS: separate instance, often using 395x/396x ports")
    print()
    print("    ▸ These ITS ports were historically exposed before ICM took over HTTP handling.")
    print("      In older deployments (or weird segmented setups), you'll still find")
    print("      ITS serving login pages and transaction forms on these ports directly.")
    print()
    print("    ▸ This check is a placeholder. Future versions of this module will:")
    print("        - Detect standalone ITS usage")
    print("        - Probe known ITS paths like /scripts/wgate/*")
    print("        - Identify the ABAP backend or service binding")
    print("        - Check for active session state via cookies")
    print()
    print("    ▸ If these ports are live, you may be interacting with a legacy")
    print("      WebGUI front-end that's decoupled from ICM — useful for fingerprinting")
    print("      older ABAP systems or restricted-access apps.")
    print("    ------------------------------------------------------------")

